// Joshua Haynes
// Spotify music de-duplicator
// 22-31 October 2025
// Maven project, Java 21

package main;

import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URI;
import java.net.URL;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.json.JSONArray;
import org.json.JSONObject;
import org.json.JSONTokener;

public class ApiConnector {
	
	private final boolean makeUnplayablePlaylist = false;
	
	private String spotifyId;
	private String authToken;
	
	private final String baseQuery = "https://api.spotify.com/v1";
	private final String queryArgs = "?limit=50&offset=";

	private final String getMyPlaylistsQuery = baseQuery + "/me/playlists" + queryArgs;
	
	private final String getOrAddOrRemoveSongsToPlaylistQuery_1 = baseQuery + "/playlists/"; // + playlistId
	private final String addOrRemoveSongsToPlaylistQuery_2 = "/tracks";
	private final String getSongsFromPlaylistQuery_2 = addOrRemoveSongsToPlaylistQuery_2 + queryArgs;
	
	private final String addToLikedSongsQuery = baseQuery + "/me/tracks";
	private final String getLikedSongsQuery = addToLikedSongsQuery + queryArgs;
	
	private final String createPlaylistQuery_1 = baseQuery + "/users/"; // + spotifyId
	private final String createPlaylistQuery_2 = "/playlists";
	private String createPlaylistQuery = "";

	private final String listDescription = "Auto generated by Music Sorter Alpha. EXCLUDE";
	
	private List<Track> likedSongsList;
	private boolean listFullyPopulated = false;
	private int retryCount = 0;
	private Set<Playlist> playlistsSet;
	private boolean setFullyPopulated = false;
	private Set<Playlist> populatedPlaylistsSet;
	private Set<String> unlikedSongIdsSet;
	private int totalSongs = 0;
	private boolean playlistCompleted = false;
	
	private Set<Track> unplayableSongsSet;
	
	public ApiConnector(String spotifyId, String authToken) {
		this.spotifyId = spotifyId;
		this.authToken = authToken;
		this.createPlaylistQuery = createPlaylistQuery_1 + spotifyId + createPlaylistQuery_2;
		
		likedSongsList = new ArrayList<Track>();
		playlistsSet = new HashSet<Playlist>();
		populatedPlaylistsSet = new HashSet<Playlist>();
		unlikedSongIdsSet = new HashSet<String>();
		
		unplayableSongsSet = new HashSet<Track>();
	}

	public void getData() {
		getAllLikedSongs();
		getAllPopulatedPlaylists();
		addOrRemoveLikedSongs(unlikedSongIdsSet, "PUT");
		
		if (makeUnplayablePlaylist) {
			createAndPopulatePlaylistRecursively("[MSA] Unplayable songs", unplayableSongsSet);
	    	System.out.println("done.");
		}
	}

	// get liked songs functions:

	private void getAllLikedSongs() {
		try {
			System.out.print("\nGetting liked songs from Spotify...");
			int offset = 0;
			while (!listFullyPopulated) {
				getLikedSongs50AtATime(offset);
				offset += 50;
				if (Math.random() < .8) { System.out.print("."); } // 80% chance
			}
			System.out.println("done.\n");

		} catch (Exception e) {
			System.out.println("\nError getting liked songs from Spotify: " + e.getMessage());
		}
	}
	
	private void getLikedSongs50AtATime(int offset) throws Exception {
		URI uri = new URI(getLikedSongsQuery + offset);
		URL url = uri.toURL();
							
		HttpURLConnection conn = (HttpURLConnection) url.openConnection();
		conn.setRequestMethod("GET");
		conn.setRequestProperty("Authorization", "Bearer " + authToken);
		conn.connect();

		int responsecode = conn.getResponseCode();
		
		if (responsecode != 200) {
			if (retryCount > 3) {
				retryCount = 0;
				throw new RuntimeException("(retried 3 times) HttpResponseCode: " + responsecode);
			}
			System.out.print("HttpResponseCode: " + responsecode + ", retrying getLikedSongs50AtATime(offset="+offset+")...");
			retryCount += 1;
			getLikedSongs50AtATime(offset); // retry recursively
		} else {
			retryCount = 0;
			
			JSONObject likedSongsJSON = new JSONObject(new JSONTokener(conn.getInputStream())); 
			JSONArray tempLikedSongsArray = likedSongsJSON.getJSONArray("items");
						
			if (tempLikedSongsArray.length() < 1) {
				listFullyPopulated = true;
				return;
			} else {
				for (int i = 0; i < tempLikedSongsArray.length(); i++ ) {
					JSONObject fullJSON = (JSONObject) tempLikedSongsArray.get(i);
					JSONObject trackJSON = (JSONObject) fullJSON.getJSONObject("track");
					
					likedSongsList.add(buildTrack(trackJSON));
				}
			}		
		}
		return;
	}
	
	// populate playlist functions:
	
	private void getAllPopulatedPlaylists() {
		System.out.print("Getting your playlists from Spotify (excludes any playlist with EXCLUDE in the description)...");
		try {
			int offset = 0;
			while (!setFullyPopulated) {
				getPlaylists50AtATime(offset);
				offset += 50;
				if (Math.random() < .8) { System.out.print("."); } // 80% chance
			}
			populateAllPlaylists();
			System.out.println("done.\n");
			
			System.out.println(totalSongs + " total songs found in " + populatedPlaylistsSet.size() + " playlists.\n");
		} catch (Exception e) {
			System.out.println("\nError getting your playlists from Spotify: " + e.getMessage());
		}
	}

	private void getPlaylists50AtATime(int offset) throws Exception {
		URI uri = new URI(getMyPlaylistsQuery + offset);
		URL url = uri.toURL();
							
		HttpURLConnection conn = (HttpURLConnection) url.openConnection();
		conn.setRequestMethod("GET");
		conn.setRequestProperty("Authorization", "Bearer " + authToken);
		conn.connect();

		int responsecode = conn.getResponseCode();
		
		if (responsecode != 200) {
			if (retryCount > 3) {
				retryCount = 0;
				throw new RuntimeException("(retried 3 times) HttpResponseCode: " + responsecode);
			}
			System.out.print("HttpResponseCode: " + responsecode + ", retrying getPlaylistIds50AtATime()...");
			retryCount += 1;
			getPlaylists50AtATime(offset); // retry recursively
		} else {
			retryCount = 0;
			JSONObject playlistsJSON = new JSONObject(new JSONTokener(conn.getInputStream()));
			JSONArray tempPlaylistsArray = playlistsJSON.getJSONArray("items");
			
			if (tempPlaylistsArray.length() < 1) {
				setFullyPopulated = true;
				return;
			} else {
				for (int c = 0; c < tempPlaylistsArray.length(); c++) {
					JSONObject playlistJSON = (JSONObject) tempPlaylistsArray.get(c);
				
					if (playlistJSON.getJSONObject("owner").getString("id").equals(spotifyId) && 
							!playlistJSON.getString("description").contains("EXCLUDE")) {
						playlistsSet.add(new Playlist(playlistJSON.getString("name"), playlistJSON.getString("id")));
					} 
				}	
			}
		}
	}
	
	private void populateAllPlaylists() throws Exception {
		for (Playlist P : playlistsSet) {
			populatePlaylist(P);
		}
	}
	
	private void populatePlaylist(Playlist playlist) throws Exception {
		playlistCompleted = false;
		int offset = 0;
		
		List<Track> playlistTracks = new ArrayList<Track>();
		
		while (!playlistCompleted) {
			playlistTracks.addAll(populatePlaylist50TracksAtATime(playlist, offset));
			offset += 50;
			if (Math.random() < .5) { System.out.print("."); } // 50% chance
		}
		
		if (playlistTracks.size() > 0) {
			totalSongs += playlistTracks.size();
			playlist.setTracks(playlistTracks);
			populatedPlaylistsSet.add(playlist);
		}
		
	}

	private List<Track> populatePlaylist50TracksAtATime(Playlist playlist, int offset) throws Exception {
		List<Track> returnList = new ArrayList<Track>();
		
		URI uri = new URI(getOrAddOrRemoveSongsToPlaylistQuery_1 + playlist.getId() + getSongsFromPlaylistQuery_2 + offset);
		URL url = uri.toURL();
							
		HttpURLConnection conn = (HttpURLConnection) url.openConnection();
		conn.setRequestMethod("GET");
		conn.setRequestProperty("Authorization", "Bearer " + authToken);
		conn.connect();

		int responsecode = conn.getResponseCode();
		
		if (responsecode != 200) {
			if (retryCount > 3) {
				retryCount = 0;
				throw new RuntimeException("(retried 3 times) HttpResponseCode: " + responsecode);
			}
			System.out.print("HttpResponseCode: " + responsecode + ", retrying getUnlikedSongsFromPlaylist()...");
			retryCount += 1;
			populatePlaylist50TracksAtATime(playlist, offset); // retry recursively
		} else {
			retryCount = 0;
			JSONObject playlistSongsJSON = new JSONObject(new JSONTokener(conn.getInputStream())); 
			JSONArray tempPlaylistSongsArray = playlistSongsJSON.getJSONArray("items");
						
			if (tempPlaylistSongsArray.length() < 1) {
				playlistCompleted = true;
				return returnList;
			} else {

				for (int i = 0; i < tempPlaylistSongsArray.length(); i++ ) {
					JSONObject fullJSON = (JSONObject) tempPlaylistSongsArray.get(i);
					JSONObject playSongJSON = (JSONObject) fullJSON.getJSONObject("track");
											
					Track tempTrack = buildTrack(playSongJSON);
					
					returnList.add(tempTrack);
					
					if (!isInLikedSongs(tempTrack.getUri())) { // unliked songs
						unlikedSongIdsSet.add(tempTrack.getId());
						likedSongsList.add(tempTrack);
					}
				}
			}
		}
		return returnList;
	}
	
	private boolean isInLikedSongs(String trackUri) {
		for (Track t : likedSongsList) {
			if (t.getUri().equals(trackUri)) {
				return true;
			}
		}
		return false;
	}
	
	// create playlist in Spotify functions:
	
	private void createAndPopulatePlaylistRecursively(String playlistName, Set<Track> songsSet) {
		if (songsSet.size() < 1) {
			System.out.println("Did not create playlist " + playlistName + " (no songs found).");
			return;
		}
		
		if (songsSet.size() <= 9000) {
			try {
				System.out.print("Creating playlist " + playlistName + " with "+songsSet.size()+" songs");
				String pId = createMSAPlaylist(playlistName);
				addOrRemoveSongsToPlaylist100AtATime(pId, songsSet, "POST");
			} catch (Exception e) {
				System.out.println("Error creating playlist " + playlistName + ": " +  e.getMessage());
			}
		} else {
			int count = 0;
			for (Set<Track> halfSet : splitSetInHalf(songsSet) ) {
				count++;
				createAndPopulatePlaylistRecursively(playlistName + count + "_", halfSet);
			}
		}
	}
	
	private Set<Set<Track>> splitSetInHalf(Set<Track> inSet) {
		Set<Set<Track>> outSets = new HashSet<Set<Track>>();
		int halfway = inSet.size() / 2;
		
		Set<Track> firstHalf = new HashSet<Track>();
		Set<Track> secondHalf = new HashSet<Track>();
		
		boolean inFirst = true;
		int setCount = 0;
		for (Track t : inSet) {
			if (inFirst) { // 1st half
				firstHalf.add(t);
			} else { // 2nd half
				secondHalf.add(t);
			}
			
			if (setCount >= halfway) {
				inFirst = false;
			}
			setCount += 1;
		}
		
		outSets.add(firstHalf);
		outSets.add(secondHalf);
		return outSets;
	}
	
	private String createMSAPlaylist(String title) throws Exception {
		URI uri = new URI(createPlaylistQuery);
		URL url = uri.toURL();
							
		HttpURLConnection conn = (HttpURLConnection) url.openConnection();
		conn.setRequestMethod("POST");
		conn.setRequestProperty("Authorization", "Bearer " + authToken);
		conn.setRequestProperty("Content-Type", "application/json");
		conn.setRequestProperty("Accept", "application/json");
		conn.setDoOutput(true);
		String jsonInputString = "{\"name\": \""+title+"\", \"description\": \""+listDescription+"\",\"public\":false}";
	
		try(OutputStream os = conn.getOutputStream()) {
		    byte[] inputBytes = jsonInputString.getBytes("utf-8");
		    os.write(inputBytes, 0, inputBytes.length);			
		}
		
		conn.connect();

		int responsecode = conn.getResponseCode();
		
		if (responsecode > 201) {
		    throw new RuntimeException("HttpResponseCode: " + responsecode);
		} else {
			JSONObject playlistIdJSON = new JSONObject(new JSONTokener(conn.getInputStream())); 
			return playlistIdJSON.getString("id");
		}
	}
	
	private void addOrRemoveSongsToPlaylist100AtATime(String playlistId, Set<Track> songsWithUris, String postOrDelete) throws Exception {
		Set<Set<String>> UriSetsOf100 = new HashSet<Set<String>>();
		Set<String> tempUriSet = new HashSet<String>();
								
		int count = 0;
		for (Track songWithUri : songsWithUris) {
			count += 1;
			tempUriSet.add(songWithUri.getUri());
			if (count > 99) {
				UriSetsOf100.add(tempUriSet);
				tempUriSet = new HashSet<String>();
				count = 0;
			}
		}
		
		if (tempUriSet.size() > 0) {
			UriSetsOf100.add(tempUriSet);
		}
		
		for (Set<String> uriSetOf100 : UriSetsOf100) {
			addOrRemove100SongsToPlaylist(playlistId, uriSetOf100, postOrDelete);
		}
	}
	
	private void addOrRemove100SongsToPlaylist(String playlistId, Set<String> songUris, String postOrDelete) throws Exception {
		String jsonInputString = createJsonFromSet(songUris, "uris", postOrDelete);
		
		if (jsonInputString.equals("{\"tracks\":]}")) {
			return;
		}
		
		URI uri = new URI(getOrAddOrRemoveSongsToPlaylistQuery_1+playlistId+addOrRemoveSongsToPlaylistQuery_2);
		URL url = uri.toURL();
							
		HttpURLConnection conn = (HttpURLConnection) url.openConnection();
		conn.setRequestMethod(postOrDelete);
		conn.setRequestProperty("Authorization", "Bearer " + authToken);
		conn.setRequestProperty("Content-Type", "application/json");
		conn.setRequestProperty("Accept", "application/json");
		conn.setDoOutput(true);
	
		try(OutputStream os = conn.getOutputStream()) {
		    byte[] inputBytes = jsonInputString.getBytes("utf-8");
		    os.write(inputBytes, 0, inputBytes.length);			
		}
		
		conn.connect();

		int responsecode = conn.getResponseCode();
		
		if (responsecode > 201) {
			if (retryCount > 3) {
				retryCount = 0;
				throw new RuntimeException("(retried 3 times) HttpResponseCode: " + responsecode);
			}
			System.out.print("HttpResponseCode: " + responsecode + ", retrying addOrRemove100SongsToPlaylist("+postOrDelete+")...");
			retryCount += 1;
			addOrRemove100SongsToPlaylist(playlistId, songUris, postOrDelete); // retry recursively
		} else {
			if (Math.random() < .8) { System.out.print("."); } // 80% chance
		}
	}
	
	// combining duplicates functions:
	
	public void handleDuplicates(Set<String> duplicateTrackIdsSet, Map<Playlist, Set<Track>> removeMap, Set<String> bestTrackIdsSet, Map<Playlist, Set<Track>> addMap) {
		
		addOrRemoveLikedSongs(duplicateTrackIdsSet, "DELETE");
		
		removeDuplicates(removeMap);
		
		addOrRemoveLikedSongs(bestTrackIdsSet, "PUT");
		
		addBestTracks(addMap);
		
		System.out.print("done.\n");
	}

	private void removeDuplicates(Map<Playlist, Set<Track>> removeMap) {
		System.out.print("Removing duplicates...");
		for (Playlist p : removeMap.keySet()) {
			try {
				addOrRemoveSongsToPlaylist100AtATime(p.getId(), removeMap.get(p), "DELETE");
			} catch (Exception e) {
				System.out.println("\nError removing duplicates from "+p.getName()+": " + e.getMessage());
			}
		}
	}
	
	private void addBestTracks(Map<Playlist, Set<Track>> addMap) {
		System.out.print("Adding best tracks...");
		for (Playlist p : addMap.keySet()) {
			try {
				addOrRemoveSongsToPlaylist100AtATime(p.getId(), addMap.get(p), "POST");
			} catch (Exception e) {
				System.out.println("\nError adding tracks to "+p.getName()+": " + e.getMessage());
			}
		}
	}
	
	private void addOrRemoveLikedSongs(Set<String> idSet, String putOrDelete) {
		if (putOrDelete.equals("PUT")) {
			System.out.print("Liking " + idSet.size() + " unliked songs...");
		} else {
			System.out.print("Unliking " + idSet.size() + " songs...");
		}
		
		Set<Set<String>> idSetsOf50 = new HashSet<Set<String>>();
		Set<String> tempIdSet = new HashSet<String>();
						
		int count = 0;
		for (String songId : idSet) {
			count += 1;
			tempIdSet.add(songId);
			if (count > 49) {
				idSetsOf50.add(tempIdSet);
				tempIdSet = new HashSet<String>();
				count = 0;
			}
		}
		
		if (tempIdSet.size() > 0) {
			idSetsOf50.add(tempIdSet);
		}
		
		try {
			for (Set<String> idSetOf50 : idSetsOf50) {
				addOrRemove50SongsFromLiked(idSetOf50, putOrDelete);
			}	
		} catch (Exception e) {
			if (putOrDelete.equals("PUT")) {
				System.out.println("\nError liking your unliked songs: " + e.getMessage());
			} else {
				System.out.println("\nError unliking your liked songs: " + e.getMessage());
			}
			
		}
//		System.out.println("done.\n");
	}
	
	private void addOrRemove50SongsFromLiked(Set<String> idSetOf50, String putOrDelete) throws Exception {
		URI uri = new URI(addToLikedSongsQuery);
		URL url = uri.toURL();
							
		HttpURLConnection conn = (HttpURLConnection) url.openConnection();
		conn.setRequestMethod(putOrDelete);
		conn.setRequestProperty("Authorization", "Bearer " + authToken);
		conn.setRequestProperty("Content-Type", "application/json");
		conn.setRequestProperty("Accept", "application/json");
		conn.setDoOutput(true);
		
		String jsonInputString = createJsonFromSet(idSetOf50, "ids", "");
							
		try(OutputStream os = conn.getOutputStream()) {
		    byte[] inputBytes = jsonInputString.getBytes("utf-8");
		    os.write(inputBytes, 0, inputBytes.length);			
		}
		
		conn.connect();

		int responsecode = conn.getResponseCode();
		
		if (responsecode > 201) {
			if (retryCount > 3) {
				retryCount = 0;
				throw new RuntimeException("(retried 3 times) HttpResponseCode: " + responsecode);
			}
			System.out.print("HttpResponseCode: " + responsecode + ", retrying addOrRemove50SongsFromLiked("+putOrDelete+")...");
			retryCount += 1;
			addOrRemove50SongsFromLiked(idSetOf50, putOrDelete); // retry recursively
		} else {
			retryCount = 0;
			if (Math.random() < .8) { System.out.print("."); } // 80% chance
		}
	}
	
	// JSON functions:
	
	private Track buildTrack(JSONObject trackJSON) {
		Track T = new Track();
		
		try {
			T.setName(trackJSON.getString("name"));
		} catch (Exception e) {
			T.setName("_");
		}
		
		try {
			T.setUri(trackJSON.getString("uri"));
		} catch (Exception e) {
			T.setUri("- - -");
		}
		
		try {
			T.setId(trackJSON.getString("id"));
		} catch (Exception e) {
			T.setId("- - -");
		}
		
		try {
			T.setLocal(trackJSON.getBoolean("is_local"));
		} catch (Exception e) {
			T.setLocal(false);
		}
		
		try {
			T.setPlayable(trackJSON.getBoolean("is_playable"));
		} catch (Exception e) {
			T.setPlayable(true);
		}
		
		if (!T.isPlayable() && !T.isLocal()) {
			unplayableSongsSet.add(T);
		}
		
		try {
			T.setDuration(trackJSON.getInt("duration_ms"));
		} catch (Exception e) {
			T.setDuration(0);
		}

		List<String> tempArtists = new ArrayList<String>();
		try {
			JSONArray tempArtistsArray = trackJSON.getJSONArray("artists");
			for (int j = 0; j < tempArtistsArray.length(); j++ ) {
				JSONObject artistJSON = (JSONObject) tempArtistsArray.getJSONObject(j);
				try {
					tempArtists.add(artistJSON.getString("name"));
				} catch (Exception e) {
					tempArtists.add("_");
				}
				
			}
			T.setArtists(tempArtists);
		} catch (Exception e) {
			T.setArtists(tempArtists);
		}
		
		try {
			JSONObject albumJSON = trackJSON.getJSONObject("album");
			try {
				T.setAlbumTracks(albumJSON.getInt("total_tracks"));
			} catch (Exception e) {
				T.setAlbumTracks(0);
			}
			try {
				T.setAlbumReleaseDate(albumJSON.getString("release_date"));
			} catch (Exception e) {
				T.setAlbumReleaseDate("-");
			}
		} catch (Exception e) {
			T.setAlbumTracks(0);
			T.setAlbumReleaseDate("-");
		}
		return T;
	}
	
	private String createJsonFromSet(Set<String> Set, String type, String postOrDelete) {
		String JsonUrisOrIds = "{\""+type+"\": [\"";
		String betweenJson = "\",\"";
		String endJson = "\"]}";
		
		if (type.equals("uris") && postOrDelete.equals("DELETE")) {
			JsonUrisOrIds = "{\"tracks\":[";
			betweenJson = "{\"uri\":\"";
			String betweenJson2 = "\"},";
			endJson = "]}";
			for (String uri : Set) {
				if (!uri.equals("- - -") && !uri.contains("spotify:local:")) {
					JsonUrisOrIds = JsonUrisOrIds + betweenJson + uri + betweenJson2;
				}
			}
			JsonUrisOrIds = JsonUrisOrIds.substring(0,JsonUrisOrIds.length()-1) + endJson;
		} else {
			for (String uriOrId : Set) {
				if (!uriOrId.equals("- - -") && !uriOrId.contains("spotify:local:")) {
					JsonUrisOrIds = JsonUrisOrIds + uriOrId + betweenJson;
				}
			}
			JsonUrisOrIds = JsonUrisOrIds.substring(0, JsonUrisOrIds.length()-betweenJson.length()) + endJson;
		}				
		return JsonUrisOrIds;
	}
	
	// getters & setters

	public List<Track> getLikedSongsList() {
		return this.likedSongsList;
	}

	public Set<Playlist> getPopulatedlaylistsSet() {
		return this.populatedPlaylistsSet;
	}

	public void setPopulatedlaylistsSet(Set<Playlist> populatedPlaylistsSet) {
		this.populatedPlaylistsSet = populatedPlaylistsSet;
	}

	public void setLikedSongsList(List<Track> likedSongsList) {
		this.likedSongsList= likedSongsList;
	}
}
